Some minor changes to the error checking changes added before
1) Changed the error outputs to STDERR instead of STDOUT.
2) Removed the exit if comskip fails.  Exiting there would leave many comskip files not cleaned up.  It is better to let it proceed to the end of the script so everything is cleaned up.

diff --git a/comchap b/comchap
--- a/comchap
+++ b/comchap
@@ -80,9 +80,9 @@ fi
 
 if [ ! -z "$lockfile" ]; then
 
-  echo "lockfile: $lockfile"
+  echo "lockfile: $lockfile" 1>&3 2>&4
   while [[ -f "$lockfile" ]]; do
-    echo "Waiting"
+    echo "Waiting" 1>&3 2>&4
     sleep 5
   done
 
@@ -117,13 +117,8 @@ if [ ! -f "$edlfile" ]; then
   $comskipPath --ini="$comskipini" "$infile"
 
   if [ ! -f "$edlfile" ] ; then
-    echo "Error running comskip. EDL File not found."  1>&3 2>&4
-
-    if [ ! -z "$lockfile" ]; then
-      rm "$lockfile"
-    fi
-
-    exit $exitcode
+    echo "Error running comskip. EDL File not found."  1>&3 2>&4 >&2
+    exitcode=-1
   fi
 fi
 
@@ -173,24 +168,24 @@ if $hascommercials ; then
       mv -f "$tempfile" "$outfile"
       echo Saved to: "$outfile"
     else
-      echo Error running ffmpeg. 1>&3 2>&4
+      echo Error running ffmpeg. 1>&3 2>&4 >&2
       exitcode=-1
     fi
   else
     if $ffmpegPath -loglevel error -hide_banner -nostdin -i "$infile" -i "$metafile" -map_metadata 1 -codec copy -y "$outfile" 1>&3 2>&4; then
       echo Saved to: "$outfile"
     else
-      echo Error running ffmpeg. 1>&3 2>&4
+      echo Error running ffmpeg. 1>&3 2>&4 >&2
       exitcode=-1
     fi
   fi
 
   if [ ! -f "$outfile" ]; then
-    echo Error, "$outfile" does not exist. 1>&3 2>&4
+    echo Error, "$outfile" does not exist. 1>&3 2>&4 >&2
     exitcode=-1
   fi
 else
-  echo No commercials found. 1>&3 2>&4
+  echo No commercials found. 1>&3 2>&4 >&2
 fi
 
 if $deleteedl ; then
